name: Publish
on:
    push:
        branches:
            - main
jobs:
    npm-publish:
        name: npm-publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - id: check
              uses: EndBug/version-check@v2.1.2
              with:
                  diff-search: true
            - name: Set up Node
              if: steps.check.outputs.changed == 'true'
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install pnpm
              if: steps.check.outputs.changed == 'true'
              run: npm install -g pnpm@10
            - name: Install
              if: steps.check.outputs.changed == 'true'
              run: pnpm install
            - name: Build
              if: steps.check.outputs.changed == 'true'
              run: pnpm build
            - name: Test
              if: steps.check.outputs.changed == 'true'
              run: pnpm test
            - name: Publish
              if: steps.check.outputs.changed == 'true'
              run: |
                  pnpm publish
                  git tag v$(jq '.version' package.json -r)
                  git push --tags
              env:
                npm_config_//registry.npmjs.org/:_authToken: ${{ secrets.NPM_AUTH_TOKEN }}
